# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  retoapi:
    image: retoapi
    build:
      context: .
      dockerfile: Reto.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5231:5231
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
